#include "throw.h"

int main()
{
    some_exception_func();
    return 0;
}